main:
  - name: 首页
    url: /
    weight: 10
  - name: 研究所简介
    url: tour
    weight: 20
  - name: 新闻动态
    url: post
    weight: 30
  - name: 科研团队
    identifier: research-team
    url: people
    weight: 40
  - name: 教授
    parent: research-team
    url: people/#group-0
    weight: 41
  - name: 副教授/副研究员
    parent: research-team
    url: people/#group-1
    weight: 42
  - name: 博士后
    parent: research-team
    url: research-team/postdoctoral
    weight: 43
  - name: 博士生
    parent: research-team
    url: research-team/doctoral
    weight: 44
  - name: 硕士生
    parent: research-team
    url: research-team/master
    weight: 45
  - name: 留学生
    parent: research-team
    url: research-team/international
    weight: 46
  - name: 科学研究
    url: publication
    weight: 60
  - name: 实验平台
    url: experimental-platform
    weight: 70
  - name: 英才诚聘
    url: recruitment
    weight: 90
